#16 total photo image and path second
smailjak/MyPhone pull request #17
Opened 2019-04-26 19:42 UTC by smailjak

Total 에 들어가서 이미지 폴더를 클릭하면 상세 이미지 파일로 들어갑니다. 

상세 이미지 파일에는 이미지 파일에 대한 이름과 ,  이미지 두개를 받아와야합니다. 
여기서 에러가 발생했습니다.

2019-04-28 03:20 UTC, ro0opf requested changes

2019-04-28 03:20 UTC, ro0opf commented on app/src/main/java/com/example/sh/androidregisterandlogin/AndroidActivity.java
>  //    databing 적용해볼까 ??? 해보자
이 주석도 제거 부탁드려요!

2019-04-28 03:20 UTC, ro0opf commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalPhoto/DetailFile/PhotoFileAdapter.java
> +    public int getItemViewType(int position) {
이 메소드는 어디에 사용되는 건가요? 
position을 parameter로 받아서 그대로 return하는데 어떤 용도인지 잘 모르겠습니다.

2019-04-28 03:20 UTC, ro0opf commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalPhoto/DetailFile/PhotoFileAdapter.java
> +    public long getItemId(int position) {
이 메소드는 어디서 사용하는 건가요?

2019-04-28 03:20 UTC, ro0opf commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalPhoto/DetailFile/PhotoFileAdapter.java
> +//    @Override
불필요한 주석은 제거해도 될 것 같습니다.

2019-04-28 03:20 UTC, ro0opf commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalPhoto/DetailFile/PhotosActivity.java
> +    boolean boolean_file;
해당 class에서만 사용한다면 private을 붙여주는게 좋을 것 같습니다.

2019-04-28 03:21 UTC, smailjak commented on app/src/main/java/com/example/sh/androidregisterandlogin/AndroidActivity.java
>  //    databing 적용해볼까 ??? 해보자
넵넵

2019-04-28 03:23 UTC, smailjak commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalPhoto/DetailFile/PhotoFileAdapter.java
> +    public int getItemViewType(int position) {
불러오는곳도 없으니 지워도 될것같은데 지울까요 ??

2019-04-28 03:24 UTC, smailjak commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalPhoto/DetailFile/PhotoFileAdapter.java
> +    public long getItemId(int position) {
TotalPhoto 에서는 이 메소드를 사용하지 않네요 ㅠㅠ 지우겠습니다

2019-04-28 03:26 UTC, smailjak commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalPhoto/DetailFile/PhotoFileAdapter.java
> +//    @Override
넵넵

2019-04-28 03:29 UTC, smailjak commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalPhoto/DetailFile/PhotosActivity.java
> +    boolean boolean_file;
int_position 은 다른 클래스에서도 사용해야하는데 , 그럼 public ArrayList 앞에 pulbic 을 지울까요 ?

2019-04-30 01:13 UTC, smailjak commented on app/src/main/java/com/example/sh/androidregisterandlogin/AndroidActivity.java
>  //    databing 적용해볼까 ??? 해보자
주석제거 완료 했습니다 .
15aee17

2019-04-30 01:13 UTC, ro0opf approved these changes

2019-04-30 01:25 UTC, merged