#36 photo update bindg
smailjak/MyPhone pull request #41
Opened 2019-05-16 12:56 UTC by smailjak

2019-05-16 23:38 UTC, ro0opf requested changes

2019-05-16 23:38 UTC, ro0opf commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalHome/Adapters/FragmentMainAdapter.java
> +    Context context;
context가 쓰이는 곳이 없는 것 같아요

2019-05-16 23:38 UTC, ro0opf commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalHome/Adapters/FragmentMessageAdapter.java
> +public class FragmentMessageAdapter extends BaseAdapter {
recyclerview로 변경하는건 어떨까요?

2019-05-16 23:38 UTC, ro0opf commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalHome/Adapters/FragmentPhonebookAdapter.java
> +public class FragmentPhonebookAdapter extends BaseRecylcerViewAdapter<AddressDataItem, FragmentPhonebookAdapter.ViewHolder> implements Filterable {
filterable은 어떤 용도인가요?

2019-05-16 23:38 UTC, ro0opf commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalHome/Adapters/PhoneBookFilter.java
> +public class PhoneBookFilter extends Filter {
filter class는 어떤 용도인가요?

2019-05-16 23:38 UTC, ro0opf commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalHome/Datas/MessageModel.java
> +        Log.d("MessageModel.test" , "datetime : " + datetime);
Log 지워도 될 것 같아요

2019-05-19 15:12 UTC, smailjak commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalHome/Adapters/FragmentMainAdapter.java
> +    Context context;
아 넵 알겠습니다 . !

2019-05-19 15:13 UTC, smailjak commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalHome/Adapters/FragmentMessageAdapter.java
> +public class FragmentMessageAdapter extends BaseAdapter {
안그래도 recyclerview 로 변경할려고 했는데 에러가 터져서 ;; ㅋㅋ 이거 수업때 다시 한번 같이 볼 수 있을까요 ?

2019-05-19 15:13 UTC, smailjak commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalHome/Adapters/FragmentPhonebookAdapter.java
> +public class FragmentPhonebookAdapter extends BaseRecylcerViewAdapter<AddressDataItem, FragmentPhonebookAdapter.ViewHolder> implements Filterable {
filterable 은 검색 용도 입니다 !

2019-05-19 15:13 UTC, smailjak commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalHome/Adapters/PhoneBookFilter.java
> +public class PhoneBookFilter extends Filter {
검색 용도 입니다. String 사용할때 equles 함수라던지 contains 함수랑 비슷하게 보시면 될  것같아요

2019-05-19 15:13 UTC, smailjak commented on app/src/main/java/com/example/sh/androidregisterandlogin/TotalHome/Datas/MessageModel.java
> +        Log.d("MessageModel.test" , "datetime : " + datetime);
넵넵

2019-05-20 11:18 UTC, ro0opf approved these changes

2019-05-20 11:21 UTC, merged